import { Component, OnInit } from '@angular/core';
import { MangaCartService } from '../manga-cart.service';
import { Manga } from './Manga';

@Component({
  selector: 'app-lista-mangas',
  templateUrl: './lista-mangas.component.html',
  styleUrls: ['./lista-mangas.component.scss']
})
export class ListaMangasComponent implements OnInit {

  public mangasList:Manga[] = [];
  
  constructor(private mangaService:MangaCartService) { 
   
  
    mangaService.mangas.subscribe((observable) => this.mangasList = observable);
    if(this.mangasList.length==0){
      mangaService.addToMangas([
        {
          id:1,
          nombre:"berserk",
          descripcion:"Guts, un ex-mercenario conocido como el 'Espadachín Negro', y en búsqueda de su venganza. Luego de una tumultuosa infancia, él finalmente encuentra a alguien a quien respeta y en quien puede confiar; y todo se desmorona cuando esta persona le arrebata todo lo importante para él, con el propósito de cumplir sus propios deseos. Ahora, siendo portador de la marca, Guts se encuentra condenado a un destino en el que es implacablemente perseguido por seres demoníacos          Encaminado en una terrible misión llena de desgracia, Guts, armado con una espada gigante y una fuerza monstruosa, no dejará que nada lo detenga, ni siquiera la misma muerte, hasta que sea capaz de tomar la cabeza de aquél que le robó toda su humanidad",
          genero:["","Fantasia","Accion","Horror","Psicologico","Tragedia","Militar","Demonios"],
          precio:60.55,
          paginas:["https://img1.tucomiconline.com/uploads/5af1fba7dfd33/Berserkv1004a_58eb928763f12.jpg"
          ,"https://img1.tucomiconline.com/uploads/5af1fba7dfd33/Berserkv1004b_58eb928763f12.jpg",
          "https://img1.tucomiconline.com/uploads/5af1fba7dfd33/Berserkv1009_58eb928763f12.jpg",
          "https://img1.tucomiconline.com/uploads/5af1fba7dfd33/Berserkv1010_58eb928763f12.jpg",
          "https://img1.tucomiconline.com/uploads/5af1fba7dfd33/Berserkv1011_58eb928763f12.jpg",
          "https://img1.tucomiconline.com/uploads/5af1fba7dfd33/Berserkv1012_58eb928763f12.jpg",
          "https://img1.tucomiconline.com/uploads/5af1fba7dfd33/Berserkv1013_58eb928763f12.jpg",
          "https://img1.tucomiconline.com/uploads/5af1fba7dfd33/Berserkv1014_58eb928763f12.jpg",
          "https://img1.tucomiconline.com/uploads/5af1fba7dfd33/Berserkv1015_58eb928763f12.jpg",
          "https://img1.tucomiconline.com/uploads/5af1fba7dfd33/Berserkv1016_58eb928763f12.jpg",
          "https://otakuteca.com/images/books/cover/8399_TMOManga5994046e71df6.jpg"],
          comprado:false,
          oferta:true,
        },
        {
          id:2,
          nombre:"Blame",
          descripcion:"Killy es un hombre de pocas palabras. Vaga, aparentemente sin fin, a través de un laberinto solitario, colosal de hormigón y acero, luchando contra los cyborgs y otras pesadillas futuristas, buscando sólo para algo llamado Genes terminal de red. Y él tiene un arma muy poderosa, que utiliza sin dudarlo siempre algo que se parezca peligro asoma su fea cabeza. ¿Quién es este hombre tranquilo, violento, decidido y cuáles son estos genes que busca? Las pequeñas comunidades que encuentran escondidas en las grietas de esta imponente, ruina distópica apenas dan lo lleva en su tesoro, conduciéndolo a encontrar enclaves más grandes de la civilización donde la gente puede revelar más sobre el mundo en que vive y de la cantera que busca.",
          genero:["","Accion","Drama","Horror","Psicologico","Ciencia ficcion","Ciberpunk"],
          precio:170.55,
          paginas:["https://img1.tucomiconline.com/uploads/5af4ae01ea8e9/blame_003_192742.jpg",
          "https://img1.tucomiconline.com/uploads/5af4ae01ea8e9/blame_004-005_192742.jpg",
          "https://img1.tucomiconline.com/uploads/5af4ae01ea8e9/blame_006_192742.jpg",
          "https://img1.tucomiconline.com/uploads/5af4ae01ea8e9/blame_007_192742.jpg",
          "https://img1.tucomiconline.com/uploads/5af4ae01ea8e9/blame_008_192742.jpg",
          "https://img1.tucomiconline.com/uploads/5af4ae01ea8e9/blame_009_192742.jpg",
          "https://img1.tucomiconline.com/uploads/5af4ae01ea8e9/blame_010_192742.jpg",
          "https://img1.tucomiconline.com/uploads/5af4ae01ea8e9/blame_011_192742.jpg",
          "https://img1.tucomiconline.com/uploads/5af4ae01ea8e9/blame_012_192742.jpg",
          "https://otakuteca.com/images/books/cover/5df9321aaa2e4.jpg"],
          comprado:false,
          oferta:false,
        },
        {
          id:3,
          nombre:"Goblin Slayer",
          descripcion:"Una joven sacerdotisa ha formado su primer grupo de aventureros, pero casi inmediatamente ellos se encuentran en apuros por los goblins. Es el Goblin Slayer quien viene a su rescate - un hombre que ha dedicado su vida a la exterminación de todos los goblins, bajo por cualquier medio necesario.",
          genero:["","accion","echi","fantasia","gore","horror"] ,
          precio: 44,
          paginas: [
          "https://img1.tucomiconline.com/uploads/5c2461956c51b/d9b9c885.jpg",
          "https://img1.tucomiconline.com/uploads/5c2461956c51b/59f01f3a.jpg",
          "https://img1.tucomiconline.com/uploads/5af54c6a1ee55/GoblinSlayer0116_574a542a0aaa1.jpg",
          "https://img1.tucomiconline.com/uploads/5af54c6a1ee55/GoblinSlayer0117_574a542a0aaa1.jpg",
          "https://img1.tucomiconline.com/uploads/5af54c6a1ee55/GoblinSlayer0118_574a542a0aaa1.jpg",
          "https://img1.tucomiconline.com/uploads/5af54c6a1ee55/GoblinSlayer0119_574a542a0aaa1.jpg",
          "https://img1.tucomiconline.com/uploads/5af54c6a1ee55/GoblinSlayer0120_574a542a0aaa1.jpg",
          "https://img1.tucomiconline.com/uploads/5af54c6a1ee55/GoblinSlayer0121_574a542a0aaa1.jpg",
          "https://img1.tucomiconline.com/uploads/5af54c6a1ee55/GoblinSlayer0122_574a542a0aaa1.jpg",
          "https://img1.tucomiconline.com/uploads/5af54c6a1ee55/GoblinSlayer0123_574a542a0aaa1.jpg",
          "https://otakuteca.com/images/books/cover/5d22c4aabc9ad.jpg",],
          comprado:false,
          oferta:true
        },
        {
          id: 4,
          nombre:"I am a Hero" ,
          descripcion:"Hideo Suzuki es un mediocre mangaka de treinta y cinco años que trabaja actualmente como asistente, y que trata desesperadamente de convertirse en el héroe de su propia vida lanzando un manga de éxito, al tiempo que intenta que vaya bien su relación con su novia y que las alucinaciones que sufre al caer la noche no le hagan perder la cabeza. Con el dinero que puede ganar con el manga, quiere comprar una casa para vivir con su novia. Sin embargo, él no se da cuenta de los inicios de una epidemia que convierte a las personas en monstruos sedientos de sangre. Mientras que la infección se está extendiendo a través de Japón, tal vez incluso del mundo, Hideo intenta sobrevivir a la epidemia y ayudar en la destrucción de la sociedad japonesa que ahora es una horda de infectados y los supervivientes que quedan en su mayoría han abandonado toda humanidad.",
          genero:["","drama","horror","psicologico","accion","misterio","sobrenatural"],
          precio: 254,
          paginas: ["https://img1.tucomiconline.com/uploads/5af173aa36509/008.jpg",
          "https://img1.tucomiconline.com/uploads/5af173aa36509/009.jpg",
          "https://img1.tucomiconline.com/uploads/5af173aa36509/010.jpg",
          "https://img1.tucomiconline.com/uploads/5af173aa36509/011.jpg",
          "https://img1.tucomiconline.com/uploads/5af173aa36509/012.jpg",
          "https://img1.tucomiconline.com/uploads/5af173aa36509/013.jpg",
          "https://img1.tucomiconline.com/uploads/5af173aa36509/014.jpg",
          "https://img1.tucomiconline.com/uploads/5af173aa36509/015.jpg",
          "https://img1.tucomiconline.com/uploads/5af173aa36509/016.jpg",
          "https://img1.tucomiconline.com/uploads/5af173aa36509/017.jpg",

          "https://otakuteca.com/images/books/cover/6102_TMOmanga091102.jpg"],
          comprado:false,
          oferta:false,
        }
        ,
        {
          id: 5,
          nombre:"Dragon Ball" ,
          descripcion:"Son Goku, es un niño muy especial que ha tenido que valerse por sí mismo en medio de la naturaleza y sin contacto con otras personas. Un día conoció a Bulma, una chica que busca las siete Esferas del Dragón, estos son elementos mágicos que al ser reunidos invocan a un dios dragón llamado Shenlong, el cual concederá un único deseo, cualquiera que este sea. Goku se une a Bulma en la búsqueda de las esferas sin imaginar que hay otros seres muy peligrosos que también las desean.",
          genero:["","Accion","Artes Marciales","Aventura","Comedia","Fantasia","Ciencia Ficcion"],
          precio: 74,
          paginas: ["https://img1.tucomiconline.com/uploads/5af31b0d62d6f/image-003.jpg",
          "https://img1.tucomiconline.com/uploads/5af31b0d62d6f/image-004.jpg",
          "https://img1.tucomiconline.com/uploads/5af31b0d62d6f/image-005.jpg",
          "https://img1.tucomiconline.com/uploads/5af31b0d62d6f/image-006.jpg",
          "https://img1.tucomiconline.com/uploads/5af31b0d62d6f/image-007.jpg",
          "https://img1.tucomiconline.com/uploads/5af31b0d62d6f/image-008.jpg",
          "https://img1.tucomiconline.com/uploads/5af31b0d62d6f/image-009.jpg",
          "https://img1.tucomiconline.com/uploads/5af31b0d62d6f/image-010.jpg",
          "https://img1.tucomiconline.com/uploads/5af31b0d62d6f/image-011.jpg",
          "https://otakuteca.com/images/books/cover/5bc9016f3c3a2.jpg"],
          comprado:false,
          oferta:true,
        },
        {
          id:6 ,
          nombre:"Akira" ,
          descripcion:"En el año 2030, 38 años después de la III Guerra Mundial. Sobre las ruinas de Tokio se alza la metrópolis de Neo-Tokio, una ciudad opresiva e inhumana donde la violencia, el terrorismo y la droga son problemas cotidianos. Las sectas religiosas y los grupos extremistas, aprovechándose de la insatisfacción de los ciudadanos, cultivan el mito de AKIRA, un 'niño cobaya' depositario de la 'energía absoluta' cuya resurrección significaría para Japón el amanecer de una nueva era. El gobierno experimenta sobre niños con poderes psíquicos para represar la ciudad. Mientras la historia se centra en dos motociclistas callejeros, Kaneda y Tetsuo, muy buenos amigos que, cuando Tetsuo sufre un choque contra un niño psíquico en una pelea de bandas, obtiene poderes que poco a poco se incrementan, provocándole alucinaciones y poderes paranormales increíbles. Mientras Tetsuo Libera caos en la ciudad y descontrol total para demostrar sus poderes creyéndose un Dios, Kaneda lo intenta detener antes que sea ",
          genero:["","Accion","Sobrenatural","Cyberpunk","Apocaliptico","Ciencia Ficcion"],
          precio: 74,
          paginas: ["https://img1.tucomiconline.com/uploads/5af402803357e/Akira-I-002_211530.jpg",
          "https://img1.tucomiconline.com/uploads/5af402803357e/Akira-I-003_211530.jpg",
          "https://img1.tucomiconline.com/uploads/5af402803357e/Akira-I-004_211530.jpg",
          "https://img1.tucomiconline.com/uploads/5af402803357e/Akira-I-005_211530.jpg",
          "https://img1.tucomiconline.com/uploads/5af402803357e/Akira-I-006_211530.jpg",
          "https://img1.tucomiconline.com/uploads/5af402803357e/Akira-I-007_211530.jpg",
          "https://img1.tucomiconline.com/uploads/5af402803357e/Akira-I-008_211530.jpg",
          "https://img1.tucomiconline.com/uploads/5af402803357e/Akira-I-009_211530.jpg",
          "https://img1.tucomiconline.com/uploads/5af402803357e/Akira-I-010_211530.jpg",
          "https://otakuteca.com/images/books/cover/9887_TMOmanga094046.jpg"],
          comprado:false,
          oferta:false,
        },
        {
          id:7 ,
          nombre:"One Punch Man" ,
          descripcion:"¡Sigue la vida de un héroe promedio que gana todas sus peleas con un solo puño! Esto le causa un montón de frustración, ahora ya no siente la adrenalina y la emoción de una dura pelea. Tal vez ese riguroso entrenamiento para volverse fuerte no valió la pena. Después de todo, ¿qué tiene de bueno tener un poder tan aplastante?",
          genero:["","Accion","Superpoderes","Comedia","Ciencia Ficcion","Sobrenatural"],
          precio: 74,
          paginas: ["https://img1.tucomiconline.com/uploads/5af2f42e6a2a4/003.jpg",
          "https://img1.tucomiconline.com/uploads/5af2f42e6a2a4/004.jpg",
          "https://img1.tucomiconline.com/uploads/5af2f42e6a2a4/005.jpg",
          "https://img1.tucomiconline.com/uploads/5af2f42e6a2a4/006.jpg",
          "https://img1.tucomiconline.com/uploads/5af2f42e6a2a4/007.jpg",
          "https://img1.tucomiconline.com/uploads/5af2f42e6a2a4/008.jpg",
          "https://img1.tucomiconline.com/uploads/5af2f42e6a2a4/009.jpg",
          "https://img1.tucomiconline.com/uploads/5af2f42e6a2a4/010.jpg",
          "https://img1.tucomiconline.com/uploads/5af2f42e6a2a4/011.jpg",
          "https://otakuteca.com/images/books/cover/5bc7cc1d2cf73.jpg"],
          comprado:false,
          oferta:false,
        },
        {
          id:8 ,
          nombre:"Parasyte: The Maxim" ,
          descripcion:"Shinichi Izumi vive con su madre y su padre en un barrio bastante tranquilo, una noche, se produce una invasión extraterrestre Los seres son llamados parásitos. Se trata de gusanos que entran en los seres humanos a los que llaman 'hosts' a través de sus orejas o la nariz, haciéndose cargo de sus cerebros Uno de ellos intentó entrar por la oreja de Shinichi para así tomar su cerebro mientras dormía ,sin embargo, es detenido y queda en su mano derecha Debido a que el parasito Migi infectó su mano en lugar de su cerebro, Shinichi puede conservar su propio intelecto. Esto les da una ventaja en la lucha contra los otros parásitos, por lo que es visto como una amenaza Shinichi se siente obligado a luchar contra otros parásitos por matar seres humanos como fuente de alimento.",
          genero:["","Accion","Superpoderes","Ciencia Ficcion","Sobrenatural","Psicologico","Horror","Drama"],
          precio: 100,
          paginas: ["https://img2.tucomiconline.com/uploads/5af3240ab3f79/RS_Kiseiju_v01_-_004.jpg",
          "https://img2.tucomiconline.com/uploads/5af3240ab3f79/RS_Kiseiju_v01_-_005.jpg",
          "https://img2.tucomiconline.com/uploads/5af3240ab3f79/RS_Kiseiju_v01_-_006.jpg",
          "https://img2.tucomiconline.com/uploads/5af3240ab3f79/RS_Kiseiju_v01_-_007.jpg",
          "https://img2.tucomiconline.com/uploads/5af3240ab3f79/RS_Kiseiju_v01_-_008.jpg",
          "https://img2.tucomiconline.com/uploads/5af3240ab3f79/RS_Kiseiju_v01_-_009.jpg",
          "https://img2.tucomiconline.com/uploads/5af3240ab3f79/RS_Kiseiju_v01_-_010.jpg",
          "https://img2.tucomiconline.com/uploads/5af3240ab3f79/RS_Kiseiju_v01_-_011.jpg",
          "https://img2.tucomiconline.com/uploads/5af3240ab3f79/RS_Kiseiju_v01_-_012.jpg",
          "https://img2.tucomiconline.com/uploads/5af3240ab3f79/RS_Kiseiju_v01_-_013.jpg",
          "https://img2.tucomiconline.com/uploads/5af3240ab3f79/RS_Kiseiju_v01_-_014.jpg",

          "https://otakuteca.com/images/books/cover/5c4e4a339cd91.jpg"],
          comprado:false,
          oferta:false,
        },
        {
          id:9 ,
          nombre:"Tokyo Ghoul" ,
          descripcion:"Al acecho en las sombras de Tokio hay seres atemorizantes conocidos como 'ghouls', que satisfacen su hambre alimentándose de humanos una vez que cae la noche. Se ha establecido una organización conocida como la Comisión de Contramedidas Ghoul (CCG) en respuesta a los constantes ataques a los ciudadanos y como un medio para purgar a estas criaturas. Sin embargo, el problema radica en identificar a los ghouls, ya que se disfrazan de humanos y viven entre las masas para que sea más fácil cazar presas. Ken Kaneki, un estudiante de primer año universitario desprevenido, se encuentra atrapado en un mundo entre humanos y ghouls cuando su cita resulta ser un ghoul después de comer su carne.Apenas sobreviviendo a este encuentro después de ser llevado a un hospital, descubre que se ha convertido en un medio ghoul como resultado de la cirugía que recibió. Incapaz de satisfacer su ansia intensa de carne humana por medios convencionales, Kaneki es acogido por amistosos ghouls que dirigen una cafetería para ayudarlo con su transición. Cuando comienza lo que cree que será una nueva vida pacífica, poco sabe que está a punto de encontrarse en el centro de una guerra entre sus nuevos camaradas y las fuerzas del CCG, y que su nueva existencia ha llamado la atención de ghouls por todo Tokio.",
          genero:["","Accion","Sobrenatural","Psicologico","Horror","Drama","Gore","Thriller"],
          precio: 150,
          paginas: ["https://img1.tucomiconline.com/uploads/5af1ba14cba5b/26_597d29a461444.jpg",
          "https://img1.tucomiconline.com/uploads/5af1ba14cba5b/27_597d29a461444.jpg",
          "https://img1.tucomiconline.com/uploads/5af1ba14cba5b/28_597d29a461444.jpg",
          "https://img1.tucomiconline.com/uploads/5af1ba14cba5b/29_597d29a461444.jpg",
          "https://img1.tucomiconline.com/uploads/5af1ba14cba5b/30_597d29a461444.jpg",
          "https://img1.tucomiconline.com/uploads/5af1ba14cba5b/31_597d29a461444.jpg",
          "https://img1.tucomiconline.com/uploads/5af1ba14cba5b/32_597d29a461444.jpg",
          "https://img1.tucomiconline.com/uploads/5af1ba14cba5b/33_597d29a461444.jpg",
          "https://img1.tucomiconline.com/uploads/5af1ba14cba5b/34_597d29a461444.jpg",
          "https://img1.tucomiconline.com/uploads/5af1ba14cba5b/35_597d29a461444.jpg",
          "https://img1.tucomiconline.com/uploads/5af1ba14cba5b/36_597d29a461444.jpg",

          "https://otakuteca.com/images/books/cover/5dbbb802c88ce.jpg"],
          comprado:false,
          oferta:false,
        },
        {
          id:10 ,
          nombre:"Ghost in the Shell Arise" ,
          descripcion:"El presunto responsable de siete atentados con bomba por todo el mundo se encuentra en la lista de la CIA de los terroristas más buscados. Han aparecido imágenes de su entrada de incógnito a Japón. Las cámaras de seguridad lo grabaron comprando glicerina para uso industrial en el mercado negro. Después de eso, su rastro se pierde ¡Averiguar el paradero del criminal tiene prioridad absoluta! Pero cuando Batou descubra que el sospechoso es un antiguo compañero de armas, el caso se complicará más de lo esperado. Esto le retrotraerá al momento en el que, siendo todavía un ranger, conoció a la Mayor Motoko Kusanagi.",
          genero:["","Accion","Psicologico","Policiaco","Militar","Drama","Gore","Cyberpunk"],
          precio: 150,
          paginas: ["https://img2.tucomiconline.com/uploads/5af46fa47be05/creditos_59a05ba5ea810.jpg",
          "https://img2.tucomiconline.com/uploads/5af46fa47be05/NsG-GITS-ARISEp01_59a05ba5ea810.jpg",
          "https://img2.tucomiconline.com/uploads/5af46fa47be05/NsG-GITS-ARISEp02_59a05ba5ea810.jpg",
          "https://img2.tucomiconline.com/uploads/5af46fa47be05/NsG-GITS-ARISEp03-04_59a05ba5ea810.jpg",
          "https://img2.tucomiconline.com/uploads/5af46fa47be05/NsG-GITS-ARISEp05-06_59a05ba5ea810.jpg",
          "https://img2.tucomiconline.com/uploads/5af46fa47be05/NsG-GITS-ARISEp07_59a05ba5ea810.jpg",
          "https://img2.tucomiconline.com/uploads/5af46fa47be05/NsG-GITS-ARISEp08_59a05ba5ea810.jpg",
          "https://img2.tucomiconline.com/uploads/5af46fa47be05/NsG-GITS-ARISEp09_59a05ba5ea810.jpg",
          "https://img2.tucomiconline.com/uploads/5af46fa47be05/NsG-GITS-ARISEp10_59a05ba5ea810.jpg",
          "https://img2.tucomiconline.com/uploads/5af46fa47be05/NsG-GITS-ARISEp11_59a05ba5ea810.jpg",
          "https://img2.tucomiconline.com/uploads/5af46fa47be05/NsG-GITS-ARISEp12_59a05ba5ea810.jpg",

          "https://otakuteca.com/images/books/cover/30181_TMOManga59a057d42d48d.jpg"],
          comprado:false,
          oferta:false,
        },
        {
          id:11 ,
          nombre:"Neon Genesis Evangelion" ,
          descripcion:"En el año 2015 la humanidad intenta recuperarse del “Segundo impacto”, una catástrofe provocada por la caída de un meteorito en la Antártida años atrás. Tras sobrevivir al deshielo de los polos y a una inmediata sucesión de guerras sin fin, los seres humanos deben enfrentarse a un nuevo y mortal peligro. Unos misteriosos seres denominados Ángeles aparecen de improvisto llevando la destrucción por donde pasan. Para frenar esta amenaza, el científico Gendo Ikari ha desarrollado los Evangelion, gigantescos robots que se convierten en la última línea de defensa para la humanidad. Uno de los primeros pilotos escogidos recibe el nombre de “Tercer Elegido”. Shinji Ikari, hijo que Gendo abandonó, se verá obligado a sondear las profundidades de sus propios recursos internos y así encontrar el valor y la fuerza, no sólo para luchar… sino para sobrevivir o arriesgarse a perderlo todo.",
          genero:["","Accion","Psicologico","Ciencia Ficcion","Drama","Tragedia","Mecha"],
          precio: 150,
          paginas: ["https://img1.tucomiconline.com/uploads/5af49b85ca846/007_211900.jpg",
          "https://img1.tucomiconline.com/uploads/5af49b85ca846/008_211900.jpg",
          "https://img1.tucomiconline.com/uploads/5af49b85ca846/009_211900.jpg",
          "https://img1.tucomiconline.com/uploads/5af49b85ca846/010_211900.jpg",
          "https://img1.tucomiconline.com/uploads/5af49b85ca846/011_211900.jpg",
          "https://img1.tucomiconline.com/uploads/5af49b85ca846/012_211900.jpg",
          "https://img1.tucomiconline.com/uploads/5af49b85ca846/013_211900.jpg",
          "https://img1.tucomiconline.com/uploads/5af49b85ca846/014_211900.jpg",
          "https://img1.tucomiconline.com/uploads/5af49b85ca846/015_211900.jpg",
          "https://img1.tucomiconline.com/uploads/5af49b85ca846/016_211900.jpg",

          "https://otakuteca.com/images/books/cover/5e7fce2c667b0.jpg"],
          comprado:false,
          oferta:false,
        }
      
      ]) 
    }
    
  }
  ngOnInit(): void {
  }
  
}
